### ISSUE TITLE
Errors on synching VCards (CardDav) with Outlook 2013 

### ISSUE THREAD

**Issue by fpPierre** [fmbiete/Z-Push-contrib#115]
Dear Francisco,

I do have the following issue.

I´m working on the current versin of the repository and nearly everything is working probably on all clients.

But there is one issue:
By using Outlook 2013 I´m not able to add or update contacts. 
I´m getting the following Error Message:

add / update:
10/12/2014 14:42:23 [ 2459] [ERROR] [XXXX@XXXX.com] BackendCardDAV->ChangeMessage - Error adding vcard '' : Woops, something's gone wrong! The CardDAV server returned the http status code 415.
10/12/2014 14:42:23 [ 2459] [ERROR] [fXXXX@XXXX.com] BackendCardDAV->ChangeMessage - vCard not updated

10/12/2014 14:44:03 [ 2459] [ERROR] [XXXX@XXXX.com] BackendCardDAV->ChangeMessage - Error updating vcard '' : Woops, something's gone wrong! The CardDAV server returned the http status code 415.
10/12/2014 14:44:03 [ 2459] [ERROR] [XXXX@XXXX.com] BackendCardDAV->ChangeMessage - vCard not updated

---

Furthermore, I switch "define('CARDDAV_SUPPORTS_SYNC', false);" onto "true"

I got Errors on getting VCards as well.

10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards in 'https://mydomain.com:443/addressbooks/XXXX@XXXX.com/collected/': Woops, something's gone wrong! The CardDAV server returned the http status code 415.
10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards
10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards in 'https://mydomain.com:443/addressbooks/XXXX@XXXX.com/family/': Woops, something's gone wrong! The CardDAV server returned the http status code 415.
10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards
10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards in 'https://mydomain.com:443/addressbooks/XXXX@XXXX.com/personal/': Woops, something's gone wrong! The CardDAV server returned the http status code 415.
10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards
10/12/2014 15:05:19 [18881] [ERROR] [XXXX@XXXX.com] BackendCardDAV->GetMessageList - Error getting the vcards in 'https://mydomain.com:443/addressbooks/XXXX@XXXX.com/work/': Woops, something's gone wrong! The CardDAV server returned the http status code 415.

This issues aren´t only existing in relation onto a Outlook 2013 Connection

I can imagine, that it is an issue with the xml-format in which outlook is linking the data.
Mybe not VCard 4.0 conform.

Can you help me with this?

**Comment by fpPierre** [comment]
Hello fmbiete,

I just ran the testing/test-carddav.php Skript and got this result:

Fatal error: Uncaught exception 'Exception' with message 'Not found!' in [...]/htdocs/include/z_carddav.php:711 
Stack trace: 
#0 [...]/htdocs/include/z_carddav.php(450): carddav_backend->simplify('<?xml version="...', true, false) 
#1 [...]/htdocs/include/z_carddav.php(467): carddav_backend->do_query_report('<?xml version="...', true, false, false) 
#2 [...]/htdocs/include/z_carddav.php(524): carddav_backend->do_query_report('<?xml version="...') 
#3 [...]/htdocs/testing-carddav.php(61): carddav_backend->get_xml_vcard('131-52C19B00-7-...') 
#4 {main} thrown in [...]/htdocs/include/z_carddav.php on line 711

Any Ideas?

**Comment by fmbiete** [comment]
Hi @fpPierre 

You must change the vcard id in the script to something existing in your account

```
// TODO: set to an existing vcard ID (you will get a list with the do_sync operation
$xml = $server->get_xml_vcard('131-52C19B00-7-7A512880');
```

**Comment by fpPierre** [comment]
Hello fmbiete,
please excuse my very late response. 

I did run the test script again and got the following result, which looks ok to me:

 http://[URL]:80/addressbooks/[USER]/ http://[URL]:80/addressbooks/[USER]/personal/
 http://[URL]:80/addressbooks/[USER]/collected/ http://[URL]:80/addressbooks/[USER]/family/
 http://[URL]:80/addressbooks/[USER]/personal/ http://[URL]:80/addressbooks/[USER]/work/
 BackendCardDAV::discoverAddressbooks() Found addressbook 'http://[URL]:80/addressbooks/[USER]/collected/'
 BackendCardDAV::discoverAddressbooks() Found addressbook 'http://[URL]:80/addressbooks/[USER]/family/'
 BackendCardDAV::discoverAddressbooks() Found addressbook 'http://[URL]:80/addressbooks/[USER]/personal/'
 BackendCardDAV::discoverAddressbooks() Found addressbook 'http://[URL]:80/addressbooks/[USER]/work/'
 http://[URL]:80/addressbooks/[USER]/personal/ 
 BE6001CA-1444-4A88-8E58-ADF5FAC40599 5a60323ea1fff2152bc13250a3580300 Wed, 10 Dec 2014 13:14:20 GMT AB1DF27F-13E2-4D04-BD8D-07BB83023869 7fdfc505283b14751ef746d4bff9bb1b Wed, 10 Dec 2014 13:14:21 GMT 4BF9E800-4B17-401E-A240-271DFB4B2754 b293d058cff9a8e1a2d6fe4b9d63a2d2 Wed, 10 Dec 2014 13:14:21 GMT 75F4FA2E-2DFC-4FE6-8275-C44B37CC0A89 5c7d6446d2e6500c05ee3e49e39173af Wed, 10 Dec 2014 13:14:21 GMT A568FCA7-B41A-4B49-AB34-96232E491E98 e2ddc315185146db6dc0b0b1469fd08b Wed, 10 Dec 2014 13:14:21 GMT D1B106B4-78A43DED-4E60182C e8e63cc4728a1d7e5c66db0bf60b0b67 Wed, 10 Dec 2014 13:14:20 GMT 8312CFED-F617642B-765BA3F6 d8d7ca4fe1da5b82af13fcc637a7cd72 Wed, 10 Dec 2014 13:14:21 GMT BD23666B-54AFFEE6-A97609BA 66fb1906160d99354aec3cafbe425b7a Wed, 10 Dec 2014 13:14:20 GMT A53DAC0C-151B2BDD-A30DA0E8 e3874b4b78bb6b2ac2439f332b0287ad Fri, 12 Dec 2014 21:17:33 GMT DDC0EED2-F5189FC5-38A9FD35 29b609ad94183fd4257613b792e65794 Fri, 12 Dec 2014 21:22:05 GMT 079BA6BA-9686DEF5-EA24F113 b2c0105d53ceb4d2a9e91aa7fa548d7a Sat, 13 Dec 2014 08:51:15 GMT 2226E857-5C8630AA-1CB504F6 3606b7365f93f97a5d71d384ee0f9e0d Sat, 20 Dec 2014 23:51:25 GMT D92F14E5-C899B132-5532E35C 6df046e1e2eb25aa6589e500a0394699 Fri, 16 Jan 2015 20:58:46 GMT ----------- 4BF9E800-4B17-401E-A240-271DFB4B2754 b293d058cff9a8e1a2d6fe4b9d63a2d2 Wed, 10 Dec 2014 13:14:21 GMT BEGIN:VCARD VERSION:3.0 PRODID:Z-Push FN:vsgd cbsv N:cbsv;vsgd;;; TEL;TYPE=HOME,VOICE:123456 UID:4BF9E800-4B17-401E-A240-271DFB4B2754 END:VCARD

**Comment by fpPierre** [comment]
Dear Francisco,

I know it has been a while but since we still haven't found a solution to this problem I would greatly appreciate if you could plase take another look at this. Thank you.

**Comment by fmbiete** [comment]
So, the test works fine.

Do the following (with an empty addressbook in the server)
1. Create a contact in Android (use the emulator if you don't have any Android device)
2. Edit the contact from Android
3. The contact should show in Android and non errors appear in the server log
4. Sync the contacts in Outlook, it should show correctly
5. Edit the contact in Outlook
6. Create a new contact in Outlook, it should show in the Android device

post your WEBXML log for the wrong operations (if they are huge use pastelink or similar)
